// Maps synonyms/variants → canonical food name
// Covers Swedish and common European/English foods
export const synonymMap: Record<string, string> = {
  // Swedish staples
  falukorv: 'falukorv',
  'falu korv': 'falukorv',
  'falkorv': 'falukorv',
  havregrynsgröt: 'havregrynsgröt',
  havregryn: 'havregrynsgröt',
  gröt: 'havregrynsgröt',
  oatmeal: 'havregrynsgröt',
  porridge: 'havregrynsgröt',
  filmjölk: 'filmjölk',
  'fil mjölk': 'filmjölk',
  knäckebröd: 'knäckebröd',
  'knäcke bröd': 'knäckebröd',
  crispbread: 'knäckebröd',
  rye_crispbread: 'knäckebröd',
  lax: 'lax',
  salmon: 'lax',
  'lax filé': 'lax',
  gravlax: 'lax',
  kaffe: 'kaffe',
  coffee: 'kaffe',
  'svart kaffe': 'kaffe',
  espresso: 'kaffe',
  latte: 'kaffe',
  bröd: 'bröd',
  bread: 'bröd',
  limpa: 'bröd',
  'vitt bröd': 'bröd',
  'råg bröd': 'bröd',
  rågbröd: 'bröd',
  toast: 'bröd',
  yoghurt: 'yoghurt',
  yogurt: 'yoghurt',
  youghurt: 'yoghurt',
  pasta: 'pasta',
  spaghetti: 'pasta',
  penne: 'pasta',
  fusilli: 'pasta',
  makaroner: 'pasta',
  tagliatelle: 'pasta',
  ris: 'ris',
  rice: 'ris',
  'basmati ris': 'ris',
  'jasmin ris': 'ris',
  potatis: 'potatis',
  potato: 'potatis',
  potatoes: 'potatis',
  'kokt potatis': 'potatis',
  'stekt potatis': 'potatis',
  kyckling: 'kyckling',
  chicken: 'kyckling',
  'kycklingfilé': 'kyckling',
  'chicken breast': 'kyckling',
  nötkött: 'nötkött',
  beef: 'nötkött',
  köttfärs: 'köttfärs',
  'malet kött': 'köttfärs',
  mince: 'köttfärs',
  'ground beef': 'köttfärs',
  tomat: 'tomat',
  tomato: 'tomat',
  tomater: 'tomat',
  gurka: 'gurka',
  cucumber: 'gurka',
  sallad: 'sallad',
  salad: 'sallad',
  'grönsallad': 'sallad',
  lettuce: 'sallad',
  ägg: 'ägg',
  egg: 'ägg',
  eggs: 'ägg',
  'scrambled eggs': 'ägg',
  mjölk: 'mjölk',
  milk: 'mjölk',
  'komjölk': 'mjölk',
  smör: 'smör',
  butter: 'smör',
  ost: 'ost',
  cheese: 'ost',
  'cheddar ost': 'ost',
  'prästost': 'ost',
  'herrgårdsost': 'ost',
  äpple: 'äpple',
  apple: 'äpple',
  banan: 'banan',
  banana: 'banan',
  apelsin: 'apelsin',
  orange: 'apelsin',
  soppa: 'soppa',
  soup: 'soppa',
  tomatsoppa: 'tomatsoppa',
  'tomato soup': 'tomatsoppa',
  linssoppa: 'linssoppa',
  'lentil soup': 'linssoppa',
  lök: 'lök',
  onion: 'lök',
  'rödlök': 'lök',
  'gul lök': 'lök',
  vitlök: 'vitlök',
  garlic: 'vitlök',
  morot: 'morot',
  carrot: 'morot',
  morötter: 'morot',
  broccoli: 'broccoli',
  blomkål: 'blomkål',
  cauliflower: 'blomkål',
  spenat: 'spenat',
  spinach: 'spenat',
  bönor: 'bönor',
  beans: 'bönor',
  linser: 'linser',
  lentils: 'linser',
  kikärtor: 'kikärtor',
  chickpeas: 'kikärtor',
  havremjölk: 'havremjölk',
  'oat milk': 'havremjölk',
  mandelmjölk: 'mandelmjölk',
  'almond milk': 'mandelmjölk',
  te: 'te',
  tea: 'te',
  'grönt te': 'te',
  'green tea': 'te',
  juice: 'juice',
  apelsinjuice: 'juice',
  'orange juice': 'juice',
  vatten: 'vatten',
  water: 'vatten',
  choklad: 'choklad',
  chocolate: 'choklad',
  glass: 'glass',
  'ice cream': 'glass',
  kaka: 'kaka',
  cake: 'kaka',
  cookie: 'kaka',
  bulle: 'bulle',
  bun: 'bulle',
  kanelbulle: 'kanelbulle',
  'cinnamon bun': 'kanelbulle',
  muesli: 'muesli',
  granola: 'muesli',
  cornflakes: 'cornflakes',
  müsli: 'muesli',
  kvarg: 'kvarg',
  quark: 'kvarg',
  kesella: 'kvarg',
  skinka: 'skinka',
  ham: 'skinka',
  'kokt skinka': 'skinka',
  tonfisk: 'tonfisk',
  tuna: 'tonfisk',
  'tonfisk på burk': 'tonfisk',
  'canned tuna': 'tonfisk',
  räkor: 'räkor',
  shrimp: 'räkor',
  prawns: 'räkor',
  sill: 'sill',
  herring: 'sill',
  'inlagd sill': 'sill',
  wienerbröd: 'wienerbröd',
  pastry: 'wienerbröd',
  smörgås: 'smörgås',
  sandwich: 'smörgås',
  macka: 'smörgås',
  salladsbar: 'sallad',
  avokado: 'avokado',
  avocado: 'avokado',
  tofu: 'tofu',
  tempeh: 'tempeh',
  seitan: 'seitan',
  koriander: 'koriander',
  coriander: 'koriander',
  basilika: 'basilika',
  basil: 'basilika',
  paprika: 'paprika',
  'bell pepper': 'paprika',
  'röd paprika': 'paprika',
  pesto: 'pesto',
  hummus: 'hummus',
  tzatziki: 'tzatziki',
  salsa: 'salsa',
  ketchup: 'ketchup',
  majonnäs: 'majonnäs',
  mayonnaise: 'majonnäs',
  senap: 'senap',
  mustard: 'senap',
  olivolja: 'olivolja',
  'olive oil': 'olivolja',
  olja: 'olja',
  oil: 'olja',
  socker: 'socker',
  sugar: 'socker',
  honung: 'honung',
  honey: 'honung',
  sylt: 'sylt',
  jam: 'sylt',
  marmelad: 'marmelad',
  marmalade: 'marmelad',
  nötter: 'nötter',
  nuts: 'nötter',
  mandlar: 'mandlar',
  almonds: 'mandlar',
  valnötter: 'valnötter',
  walnuts: 'valnötter',
  cashewnötter: 'cashewnötter',
  cashews: 'cashewnötter',
  jordnötter: 'jordnötter',
  peanuts: 'jordnötter',
  frön: 'frön',
  seeds: 'frön',
  chiafrön: 'chiafrön',
  'chia seeds': 'chiafrön',
  solrosfrön: 'solrosfrön',
  'sunflower seeds': 'solrosfrön',
  pumpafrön: 'pumpafrön',
  'pumpkin seeds': 'pumpafrön',
  pizza: 'pizza',
  hamburgare: 'hamburgare',
  burger: 'hamburgare',
  hamburger: 'hamburgare',
  tacos: 'tacos',
  taco: 'tacos',
  wraps: 'wraps',
  wrap: 'wraps',
  sushi: 'sushi',
  ramen: 'ramen',
  curry: 'curry',
  lasagne: 'lasagne',
  lasagna: 'lasagne',
  köttbullar: 'köttbullar',
  meatballs: 'köttbullar',
  pannkaka: 'pannkaka',
  pancake: 'pannkaka',
  pannkakor: 'pannkaka',
  våffla: 'våffla',
  waffle: 'våffla',
  müslibröd: 'bröd',
  'fullkornsbröd': 'bröd',
  'whole grain bread': 'bröd',
  'sourdough': 'bröd',
  surdegsbröd: 'bröd',
}

// Known Swedish/European brands to strip
export const knownBrands = [
  'scan',
  'arla',
  'felix',
  'findus',
  'pågen',
  'fazer',
  'oatly',
  'ica',
  'coop',
  'eldorado',
  'garant',
  'kungsörnen',
  'schulstad',
  'ekströms',
  'calve',
  'heinz',
  'kellogs',
  'kelloggs',
  'nestle',
  'nestlé',
  'knorr',
  'maggi',
  'barilla',
  'de cecco',
  'santa maria',
  'orkla',
  'garant',
  'kiviks',
  'önos',
  'abba',
  'skagenröra',
  'skånemejerier',
  'valio',
  'danone',
  'yoplait',
  'alpro',
]

// Modifiers to strip before lookup
export const modifiers = [
  'laktosfri',
  'laktosfritt',
  'glutenfri',
  'glutenfritt',
  'ekologisk',
  'ekologiskt',
  'light',
  'lite',
  'fettfri',
  'fettfritt',
  'mager',
  'magert',
  'fullkorns',
  'fullkorn',
  'hemlagad',
  'hemgjord',
  'nyttig',
  'nyttigt',
  'rik på protein',
  'proteinrik',
  'färsk',
  'fryst',
  'konserverad',
  'saltad',
  'osaltad',
  'rökt',
  'grillad',
  'stekt',
  'kokt',
  'rå',
  'organic',
  'free range',
  'low fat',
  'fat free',
  'skimmed',
  'semi-skimmed',
  'whole',
  'reduced fat',
  'sugar free',
  'sockerfri',
]
